name: pytest

on:
  push
  pull_request

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rye
        run:  curl -sSf https://rye-up.com/get | bash
      - name: Install Dependencies
        run: rye sync
      # pytest を実行する
      - name: Run Tests
        run: rye run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
